services:
  ardupilot-sitl:
    image: ${GHCR_NAMESPACE:-ghcr.io/davidnoronha1/mira_sim}-ardupilot-sitl:${IMAGE_TAG:-latest}
    build:
     context: .
     dockerfile: Dockerfile
    platform: linux/amd64
    tty: true
    environment:
      - VEHICLE=ArduSub
      - MODEL=vectored
      - PATH=/usr/local/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ./ardupilot:/ardupilot_data
      - ./docker/ardusub_frame_config.parm:/ardusub_frame_config.parm:ro
    network_mode: host
    entrypoint: /bin/bash
    command: >
      -c "
      cd /ardupilot_data && /ardupilot/Tools/autotest/sim_vehicle.py -N -f vectored_6dof -v ArduSub --console --model JSON:127.0.0.1 --custom-location=56.136459,-2.706819,0,0 --add-param-file=/ardusub_frame_config.parm --out=udp:0.0.0.0:14550 --out=udp:0.0.0.0:14555"
  mira_sim:
    image: ${GHCR_NAMESPACE:-ghcr.io/davidnoronha1/mira_sim}-stonefish:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: stonefish.Dockerfile
    platform: linux/amd64
    tty: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
    entrypoint: /bin/bash
